// <auto-generated />
using HotelAppDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelAppDemo.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20230719011918_seedingDataOfRoomTable")]
    partial class seedingDataOfRoomTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelAppDemo.Model.Amenities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("amenities");
                });

            modelBuilder.Entity("HotelAppDemo.Model.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("hotel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Paris",
                            Country = "France",
                            Name = "Async Inn",
                            Phone = "00560078",
                            State = " Paris",
                            StreetAdress = "Paris-France"
                        },
                        new
                        {
                            Id = 2,
                            City = "Amman",
                            Country = "Jordan",
                            Name = "Async Inn",
                            Phone = "00962788996677",
                            State = " Amman",
                            StreetAdress = "DownTawn"
                        },
                        new
                        {
                            Id = 3,
                            City = "Qairo",
                            Country = "Egypt",
                            Name = "Async Inn",
                            Phone = "0156005098",
                            State = "Qairo",
                            StreetAdress = "SalahSalem"
                        });
                });

            modelBuilder.Entity("HotelAppDemo.Model.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("layout")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("room");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "RainTrain",
                            layout = 2
                        },
                        new
                        {
                            Id = 2,
                            Name = "GreenForest",
                            layout = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "RainTrain",
                            layout = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
