// <auto-generated />
using HotelAppDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelAppDemo.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    partial class HotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelAppDemo.Model.Amenities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ac"
                        },
                        new
                        {
                            Id = 2,
                            Name = "CoffeMaker"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sawna"
                        });
                });

            modelBuilder.Entity("HotelAppDemo.Model.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("hotel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Paris",
                            Country = "France",
                            Name = "Async Inn",
                            Phone = "00560078",
                            State = " Paris",
                            StreetAdress = "Paris-France"
                        },
                        new
                        {
                            Id = 2,
                            City = "Amman",
                            Country = "Jordan",
                            Name = "Async Inn",
                            Phone = "00962788996677",
                            State = " Amman",
                            StreetAdress = "DownTawn"
                        },
                        new
                        {
                            Id = 3,
                            City = "Qairo",
                            Country = "Egypt",
                            Name = "Async Inn",
                            Phone = "0156005098",
                            State = "Qairo",
                            StreetAdress = "SalahSalem"
                        });
                });

            modelBuilder.Entity("HotelAppDemo.Model.HotelRoom", b =>
                {
                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<bool>("PetFrienndly")
                        .HasColumnType("bit");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.HasKey("HotelId", "RoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("hotelRooms");
                });

            modelBuilder.Entity("HotelAppDemo.Model.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("layout")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("room");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "RainTrain",
                            layout = 2
                        },
                        new
                        {
                            Id = 2,
                            Name = "GreenForest",
                            layout = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "RainTrain",
                            layout = 3
                        });
                });

            modelBuilder.Entity("HotelAppDemo.Model.RoomAmenity", b =>
                {
                    b.Property<int>("AmenityId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("AmenityId", "RoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("roomAmenities");
                });

            modelBuilder.Entity("HotelAppDemo.Model.HotelRoom", b =>
                {
                    b.HasOne("HotelAppDemo.Model.Hotel", "Hotel")
                        .WithMany("HotelRooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelAppDemo.Model.Room", "Room")
                        .WithMany("HotelRooms")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelAppDemo.Model.RoomAmenity", b =>
                {
                    b.HasOne("HotelAppDemo.Model.Amenities", "Amenity")
                        .WithMany("RoomAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelAppDemo.Model.Room", "Room")
                        .WithMany("RoomAmenities")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelAppDemo.Model.Amenities", b =>
                {
                    b.Navigation("RoomAmenities");
                });

            modelBuilder.Entity("HotelAppDemo.Model.Hotel", b =>
                {
                    b.Navigation("HotelRooms");
                });

            modelBuilder.Entity("HotelAppDemo.Model.Room", b =>
                {
                    b.Navigation("HotelRooms");

                    b.Navigation("RoomAmenities");
                });
#pragma warning restore 612, 618
        }
    }
}
